#!/home/samhaug/anaconda2/bin/python

import numpy as np
from matplotlib import pyplot as plt
import obspy
import seispy
from os import listdir


def main():
    syn_dir = listdir('/home/samhaug/work1/SP_brazil_sims/SVaxi/shareseismos/')

    fig,ax = plt.subplots()
    for ii in syn_dir:
        print ii
        st = obspy.read('/home/samhaug/work1/SP_brazil_sims/SVaxi/shareseismos/'+ii+'/*170.R')
        tr = grab_conversion(st[0])
        t = np.linspace(0,tr.stats.endtime-tr.stats.starttime,\
                        num=tr.stats.npts)
    plt.show()


def grab_conversion(tr):
    tr.stats.sac['o'] *= -202
    a = seispy.data.phase_window(tr,phase=['S1800P'],window=(-100,10))
    return a

main()






