#!/home/samhaug/anaconda2/bin/python

import numpy as np
from matplotlib import pyplot as plt
import obspy
import seispy
from os import listdir
from subprocess import call


def main():
    dir_name = '/home/samhaug/work1/SP_brazil_sims/SVaxi/shareseismos/'
    prem_dir = '/home/samhaug/work1/SP_brazil_sims/SVaxi/share_first/smoothedprem/'
    syn_dir = sorted(listdir(dir_name))

    fig,ax = plt.subplots()
    st_prem = obspy.read(prem_dir+'/*170.R')
    #st_prem.normalize()
    prem = grab_conversion(st_prem[0])
    prem.data += -1*np.mean(prem.data)

    for ii in syn_dir:
        if 'dVs10' in ii:
            name = ii.split('_')[1][1::]
            st = obspy.read(dir_name+ii+'/*170.R')
            #st.normalize()
            tr = grab_conversion(st[0])
            t = np.linspace(0,tr.stats.endtime-tr.stats.starttime,num=tr.stats.npts)
            conv = tr.data-prem.data
            #conv += -1*np.mean(conv)
            tr.data += -1*np.mean(tr.data)
            #plt.plot(t,prem.data,label=ii)
            conv += -1*conv[0]
            ax.plot(t,conv,label=str(int(name))+r'$^\circ$')

        #elif 'dVs5' in ii:
        #    print ii
        #    name = ii.split('_')[1][1::]
        #    st = obspy.read(dir_name+ii+'/*170.R')
        #    #st.normalize()
        #    tr = grab_conversion(st[0])
        #    t = np.linspace(0,tr.stats.endtime-tr.stats.starttime,num=tr.stats.npts)
        #    conv = tr.data-prem.data
        #    #conv += -1*np.mean(conv)
        #    tr.data += -1*np.mean(tr.data)
        #    #plt.plot(t,prem.data,label=ii)
        #    conv += -1*conv[0]
        #    ax[1].plot(t,conv,label=name)
        #    ax[1].legend()

        #ax[1].legend()

    ax.grid()
    ax.set_xlabel('Seconds')
    ax.legend()
    plt.tight_layout()
    plt.savefig('svaxi_conversion.pdf')
    call('evince svaxi_conversion.pdf',shell=True)


def grab_conversion(tr):

    tr.stats.sac['o'] += -202
    a = seispy.data.phase_window(tr,phase=['S1800P'],window=(-20,10))
    #a.detrend()
    return a

main()






